spring:
  application:
    name=security
  flyway:
    table: schema_version
  datasource:
    url: jdbc:postgresql://localhost:5432/today
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
      minimum-idle: 5
      pool-name: HikariInternalResPool
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    secret: YM6NgEfajcaJj8KweqZ9ANhaPK6C2zgGasARAbwSFzmsFJey4jK8rMnyjr2ZbJnLz9QzH4mRuZMucghbApEy5CjZ46xEmwT2HasCLfjyzST3WtsWNyyuKMUQ47LsxrJUrnJaEbWpCeuGmQ4MCRAjDAc9zGKCwEC4QDEJuKnaFXn843SsYawWBoDEykDeWSzgME2zqpPwZeBu2HoTQgwbUbHtaCqXBUfDyT8BgZBLmbnNHzZXL9PgtxwaatHomycN
